# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjdmYjBlMDQ1NDAxYzZkMmMzYjM1ZWEyYzU4ODBkYmEyMmRlODRkZDExZTU0MmEyNTZlZTU0NjJjMzE2MzM2N2FhNmE1ZjIzMDgxNWM3YTRhNzg0OWE3NjY2NTk4ODIxZDFiMzRkYjUzNThmNDkzZTdlMGVlM2MxNjQ3OTA0ZTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
